### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [kbanico/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kbanico** [comment]
Hi
Thank you.
I added this to my application.html.erb within the head tag.
<meta name="viewport" content="width=device-width, initial-scale=1">
and have push it to github and updated my code for heroku :)
thank you again!

**Comment by Mikeysax** [comment]
:+1:
